adminUser: admin
adminPassword: prom-operator
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-http"
  hosts:
    - grafana.merldev.com
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.merldev.com
persistence:
  enabled: false
